name: Promote to Main

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  promote:
    if: github.ref == 'refs/heads/develop'
    name: Promote if tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge develop into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/develop --no-ff -m "Auto-merge develop into main [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ github.token }}
